### ISSUE TITLE
1 fichier PREMIUM issue

### ISSUE THREAD

**Issue by dedelastuce** [pyload/pyload#1042]
Hello
I still have a Problem with Pyload and 1fichier in premium mode

It downloads well but the file isnt renamed : 
For instance when i download with this kind of link : https://1fichier.com/?c7qzf29jal. My file will be c7qzf29jal (without any extension)....

Can you help me to solve my problem?
LOG : 
14.01.2015 09:16:22	INFO	ExtractArchive: Check package: https://1fichier.com/?c7qzf29jal
14.01.2015 09:16:22	INFO	Package finished: https://1fichier.com/?c7qzf29jal
14.01.2015 09:16:22	INFO	Download finished: c7qzf29jal

Thx a lot

**Comment by dedelastuce** [comment]
New issue : 
All my links on one fichier doesn't work
Files exist on Onefichier

16.01.2015 17:05:06	INFO	ExtractArchive: No files found to extract
16.01.2015 17:05:06	INFO	ExtractArchive: Check package: http://hl1yai.1fichier.com/
16.01.2015 17:05:06	INFO	Package finished: http://hl1yai.1fichier.com/
16.01.2015 17:05:06	INFO	Download skipped: Unknown due to OneFichierCom

**Comment by vuolter** [comment]
Disable addons ExtractArchive and SkipRev for now.

**Comment by dedelastuce** [comment]
thx vuolter but it doesnt work
My pyload skip all files : 
64    17.01.2015 01:56:40	INFO	pyLoad is up and running
65	17.01.2015 01:56:42	INFO	UpdateManager: No new pyLoad version available
66	17.01.2015 01:56:42	INFO	UpdateManager: No plugin updates available
67	17.01.2015 01:57:32	INFO	Download skipped: Unknown due to OneFichierCom
68	17.01.2015 01:57:34	INFO	Download skipped: Unknown due to OneFichierCom
69	17.01.2015 01:57:36	INFO	Download skipped: Unknown due to OneFichierCom
70	17.01.2015 01:57:38	INFO	Download skipped: Unknown due to OneFichierCom
71	17.01.2015 01:57:40	INFO	Download skipped: Unknown due to OneFichierCom
72	17.01.2015 01:57:42	INFO	Download skipped: Unknown due to OneFichierCom
73	17.01.2015 01:57:44	INFO	Download skipped: Unknown due to OneFichierCom
74	17.01.2015 01:57:46	INFO	Download skipped: Unknown due to OneFichierCom
75	17.01.2015 01:57:48	INFO	Download skipped: Unknown due to OneFichierCom
76	17.01.2015 01:57:48	INFO	Package finished: fiction

**Comment by dedelastuce** [comment]
Today itt works !!!
Files are Ok and renamed... Strange...

**Comment by vuolter** [comment]
I just fixed the ddl recognition, maybe your issue was due that. XD

**Comment by dedelastuce** [comment]
No there is still a problem !!!
It worked because i wasnt connected as premium user.....
When i connect pyload download an "Unknown" file....

**Comment by vuolter** [comment]
Try disabling UnSkipOnFail addon... I really don't know... works for me, free + premium. :S

**Comment by dedelastuce** [comment]
Ok i ll try but I dont think its that.
Can you send me your OneFichierCom.py file?
I ve got that in mine : 
# -*- coding: utf-8 -*-

import re

from module.plugins.internal.SimpleHoster import SimpleHoster, create_getInfo


class OneFichierCom(SimpleHoster):
    __name__    = "OneFichierCom"
    __type__    = "hoster"
    __version__ = "0.73"

    __pattern__ = r'https?://(?:www\.)?(?:(?P<ID1>\w+)\.)?(?P<HOST>1fichier\.com|alterupload\.com|cjoint\.net|d(es)?fichiers\.com|dl4free\.com|megadl\.fr|mesfichiers\.org|piecejointe\.net|pjointe\.com|tenvoi\.com)(?:/\?(?P<ID2>\w+))?'

    __description__ = """1fichier.com hoster plugin"""
    __license__     = "GPLv3"
    __authors__     = [("fragonib", "fragonib[AT]yahoo[DOT]es"),
                       ("the-razer", "daniel_ AT gmx DOT net"),
                       ("zoidberg", "zoidberg@mujmail.cz"),
                       ("imclem", None),
                       ("stickell", "l.stickell@yahoo.it"),
                       ("Elrick69", "elrick69[AT]rocketmail[DOT]com"),
                       ("Walter Purcaro", "vuolter@gmail.com")]


    NAME_PATTERN = r'>FileName :</td>\s*<td.*>(?P<N>.+?)<'
    SIZE_PATTERN = r'>Size :</td>\s*<td.*>(?P<S>[\d.,]+) (?P<U>[\w^_]+)'

    OFFLINE_PATTERN = r'File not found !\s*<'

    COOKIES = [("1fichier.com", "LG", "en")]

    WAIT_PATTERN = r'>You must wait (\d+)'


    def setup(self):
        self.multiDL = self.premium
        self.resumeDownload = True


    def handle(self, reconnect):
        m = re.search(self.WAIT_PATTERN, self.html)
        if m:
            wait_time = int(m.group(1)) * 60

            self.wait(wait_time, reconnect)
            self.retry(reason="You have to wait been each free download")

        id = self.info['ID1'] or self.info['ID2']
        url, inputs = self.parseHtmlForm('action="https://1fichier.com/\?%s' % id)

        if not url:
            self.fail(_("Download link not found"))

        if "pass" in inputs:
            inputs['pass'] = self.getPassword()

        inputs['submit'] = "Download"

        self.download(url, post=inputs)


    def handleFree(self):
        return self.handle(True)


    def handlePremium(self):
        return self.handle(False)


getInfo = create_getInfo(OneFichierCom)

**Comment by vuolter** [comment]
Latest version is 0.77, so turn off debug mode, enable UpdateManager, finally restart pyload to allow the self-update.

**Comment by dedelastuce** [comment]
Hi thanks for the info
I think you have find my problem.... My pyload do not update my plugins......
I m still in 0.73 version on Onefichier 
I m not in debug mode and I have update manager activated : 

762	19.01.2015 10:00:36	INFO	UpdateManager: No plugin updates available
761	19.01.2015 10:00:36	INFO	UpdateManager: No new pyLoad version available
760	19.01.2015 10:00:33	INFO	pyLoad is up and running

**Comment by dedelastuce** [comment]
Do you know what to do?
Reinstall All plugin folder?
Something else?
Thanks

**Comment by vuolter** [comment]
Delete userplugins folder + accounts.conf in config directory. Then restart pyload.

**Comment by dedelastuce** [comment]
Thanks for the advise 
need I delete my premium account first?
Thanks

**Comment by vuolter** [comment]
Deleting accounts.conf remove all your insered accounts.
Yep, all is under the .pyload directory.

**Comment by dedelastuce** [comment]
Ok nice 
Thanks a lot !!!!!
It seems to work
have a nice day and thx very much

**Comment by olivvv59** [comment]
yes !!!
I've the same problem for january with my premium account.
I don't find a solution and find this page.

I try your solution and come back

**Comment by olivvv59** [comment]
I disable UnSkipOnFail addon .. it seems to work now ..

**Comment by olivvv59** [comment]
no, i was in a free account.the problem was still here.

I have to :
"Delete folder userplugins and file accounts.conf in config directory. Then restart pyload."

thanks !!!!

**Comment by yann19fr** [comment]
Same issue for me. After deleting folder userplugins and file accounts.conf then enter my premium account, the filename is incorrect
Example 0c9k9mjxbj (without any extension)

Here the logs : 
> 366	31.01.2015 11:06:09	INFO	Added package test containing 1 links
367	31.01.2015 11:06:10	INFO	Download starts: https://1fichier.com/?0c9k9mjxbj
368	31.01.2015 11:06:18	INFO	OneFichierCom: Direct download link detected
369	31.01.2015 11:06:38	INFO	Download aborted: 0c9k9mjxbj
370	31.01.2015 11:10:09	INFO	Added package test containing 1 links
371	31.01.2015 11:10:10	INFO	Download starts: 0c9k9mjxbj

**Comment by olivvv59** [comment]
I speak to fast .

Now , i' ve the same thing.

**Comment by olivvv59** [comment]
When the download fails, it takes the good name in the list.

**Comment by vuolter** [comment]
No debug log, no fun. :P

**Comment by yann19fr** [comment]
Here the log a download : 

> 264	01.02.2015 12:52:22	DEBUG	Redirected import module.plugins.hoster.OneFichierCom -> userplugins.hoster.OneFichierCom
265	01.02.2015 12:52:22	INFO	Added package Test Premium containing 1 links
266	01.02.2015 12:52:22	DEBUG	Run Info Fetching for OneFichierCom
267	01.02.2015 12:52:23	DEBUG	Finished Info Fetching for OneFichierCom
268	01.02.2015 12:52:23	INFO	Download starts: Unknown
269	01.02.2015 12:52:23	DEBUG	OneFichierCom: File info (BEFORE): {}
270	01.02.2015 12:52:24	DEBUG	OneFichierCom: File info (AFTER): {'status': 3, 'url': u'http://102q6v.1fichier.com/', 'size': 0, 'name': u'Unknown', 'pattern': {'HOST': u'1fichier.com', 'ID2': None, 'ID1': u'102q6v'}}
271	01.02.2015 12:52:24	DEBUG	OneFichierCom: File name: Unknown | Unknown
272	01.02.2015 12:52:24	DEBUG	OneFichierCom: File status: queued | File info: {'status': 3, 'url': u'http://102q6v.1fichier.com/', 'size': 0, 'name': u'Unknown', 'pattern': {'HOST': u'1fichier.com', 'ID2': None, 'ID1': u'102q6v'}}
273	01.02.2015 12:52:24	DEBUG	OneFichierCom: Looking for direct download link...
274	01.02.2015 12:52:24	DEBUG	OneFichierCom: Redirect #0 to: http://102q6v.1fichier.com/
275	01.02.2015 12:52:24	DEBUG	OneFichierCom: Redirect #1 to: https://102q6v.1fichier.com/
276	01.02.2015 12:52:25	DEBUG	OneFichierCom: Redirect #2 to: https://a-2.1fichier.com/c1050358973
277	01.02.2015 12:52:30	INFO	OneFichierCom: Direct download link detected
278	01.02.2015 12:52:37	DEBUG	Content-Disposition: Breaking.Bad.S04E01.VOSTFR.DVDRip.XviD-GKS.avi filename*=UTF-8Breaking.Bad.S04E01.VOSTFR.DVDRip.XviD-GKS.avi
279	01.02.2015 12:52:37	DEBUG	Chunked with range 122531463-245062926
280	01.02.2015 12:52:37	DEBUG	Chunked with range 245062926-
281	01.02.2015 12:55:33	INFO	Download finished: Unknown
282	01.02.2015 12:55:33	INFO	Package finished: Test Premium
283	01.02.2015 12:55:33	DEBUG	ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
284	01.02.2015 12:55:33	INFO	ExtractArchive: Check package: Test Premium
285	01.02.2015 12:55:35	DEBUG	All downloads processed
286	01.02.2015 12:55:35	INFO	ExtractArchive: No files found to extract
287	01.02.2015 12:55:35	DEBUG	ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
288	01.02.2015 12:55:35	DEBUG	All downloads finished

**Comment by olivvv59** [comment]
you're right 

```javascript
01.02.2015 14:07:47	INFO	UpdateManager: No plugin updates available
166	01.02.2015 14:07:48	DEBUG	OneFichierCom: File info (AFTER): {'status': 3, 'url': u'https://1fichier.com/?priniv', 'size': 0, 'name': u'priniv', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'priniv', 'ID1': None}}
167	01.02.2015 14:07:48	DEBUG	OneFichierCom: File name: priniv | Unknown
168	01.02.2015 14:07:48	DEBUG	OneFichierCom: File status: queued | File info: {'status': 3, 'url': u'https://1fichier.com/?priniv', 'size': 0, 'name': u'priniv', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'priniv', 'ID1': None}}
169	01.02.2015 14:07:48	DEBUG	OneFichierCom: Looking for direct download link...
170	01.02.2015 14:07:48	DEBUG	OneFichierCom: Redirect #0 to: https://1fichier.com/?priniv
171	01.02.2015 14:07:50	DEBUG	OneFichierCom: Redirect #1 to: https://a-2.1fichier.com/c1050589560
172	01.02.2015 14:07:56	INFO	OneFichierCom: Direct download link detected
173	01.02.2015 14:08:03	DEBUG	Content-Disposition: 017 - La Belle Et Le Clochard - Multi.mkv filename*=UTF-8017+-+La+Belle+Et+Le+Clochard+-+Multi.mkv
174	01.02.2015 14:08:03	DEBUG	Chunked with range 1954226796-3908453592
175	01.02.2015 14:08:03	DEBUG	Chunked with range 3908453592-
```

**Comment by vuolter** [comment]
Aaargh... the content-disposition issue... my nemesis. u_u

**Comment by celena007** [comment]
Hello i have the same problem

671	09.02.2015 13:47:15	INFO	Download starts: hgc15ic3p3
672	09.02.2015 13:47:15	DEBUG	OneFichierCom: Update file info...
673	09.02.2015 13:47:15	DEBUG	OneFichierCom: Previous file info: {}
674	09.02.2015 13:47:15	DEBUG	Finished Info Fetching for OneFichierCom
675	09.02.2015 13:47:16	DEBUG	OneFichierCom: Current file info: {'status': 3, 'url': u'https://1fichier.com/?hgc15ic3p3', 'size': 0, 'name': u'hgc15ic3p3', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'hgc15ic3p3', 'ID1': None}}
676	09.02.2015 13:47:16	DEBUG	OneFichierCom: File name: hgc15ic3p3 | Unknown
677	09.02.2015 13:47:16	DEBUG	OneFichierCom: File status: queued
678	09.02.2015 13:47:16	DEBUG	OneFichierCom: Looking for direct download link...
679	09.02.2015 13:47:16	DEBUG	OneFichierCom: Redirect #0 to: https://1fichier.com/?hgc15ic3p3
680	09.02.2015 13:47:16	DEBUG	OneFichierCom: Redirect #1 to: https://a-8.1fichier.com/c1075606568
681	09.02.2015 13:47:17	INFO	Download starts: ewmochqemq
691	09.02.2015 13:47:22	DEBUG	Content-Disposition: [Bonta-fansub]Astarotte no Omocha!.MaChO@zone-telechargement.com.part1.rar filename*=UTF-8%5bBonta-fansub%5dAstarotte+no+Omocha%21.MaChO%40zone-telechargement.com.part1.rar
692	09.02.2015 13:47:22	DEBUG	Chunked with range 1431655766-2863311532
693	09.02.2015 13:47:22	DEBUG	Chunked with range 2863311532-

**Comment by vuolter** [comment]
@celena007 OS and platform, please.

**Comment by celena007** [comment]
sorry i have forgot it :
it run on my qnap nas

System
Python: 	2.5.5 (r255:77872, May 16 2010, 10:32:26) [GCC 4.2.1]
OS: 	posix linux2 Linux NAS 3.12.6 #1 SMP Mon Jan 26 15:37:31 CST 2015 x86_64
pyLoad version: 	0.4.9

**Comment by vuolter** [comment]
@celena007 I'm gonna try it on an enviroment like yours and let you know.

**Comment by olivvv59** [comment]
With Some Files, it works ...

```
10.02.2015 15:05:49	INFO	Download starts: kpti0z
157	10.02.2015 15:05:49	DEBUG	OneFichierCom: Update file info...
158	10.02.2015 15:05:49	DEBUG	OneFichierCom: Previous file info: {}
159	10.02.2015 15:05:51	DEBUG	OneFichierCom: Current file info: {'status': 3, 'url': u'https://1fichier.com/?kpti0z', 'size': 0, 'name': u'kpti0z', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'kpti0z', 'ID1': None}}
160	10.02.2015 15:05:51	DEBUG	OneFichierCom: File name: kpti0z | File size: Unknown
161	10.02.2015 15:05:51	DEBUG	OneFichierCom: File status: queued
162	10.02.2015 15:05:51	DEBUG	OneFichierCom: Looking for direct download link...
163	10.02.2015 15:05:51	DEBUG	OneFichierCom: Redirect #0 to: https://1fichier.com/?kpti0z
164	10.02.2015 15:05:52	DEBUG	OneFichierCom: Direct download link not found
165	10.02.2015 15:05:53	DEBUG	OneFichierCom: Update file info...
166	10.02.2015 15:05:53	DEBUG	OneFichierCom: Previous file info: {'status': 3, 'url': u'https://1fichier.com/?kpti0z', 'size': 0, 'name': u'kpti0z', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'kpti0z', 'ID1': None}}
167	10.02.2015 15:05:53	DEBUG	OneFichierCom: Current file info: {'status': 2, 'name': u'086 - Cars - Multi.mkv', 'url': u'https://1fichier.com/?kpti0z', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'ID1': None, 'ID2': u'kpti0z', 'S': u'9.84', 'N': u'086 - Cars - Multi.mkv'}, 'size': 10565619548.16}
168	10.02.2015 15:05:53	DEBUG	OneFichierCom: File name: 086 - Cars - Multi.mkv | File size: 10565619548
169	10.02.2015 15:05:53	DEBUG	OneFichierCom: Update file info...
170	10.02.2015 15:05:53	DEBUG	OneFichierCom: Previous file info: {'status': 2, 'name': u'086 - Cars - Multi.mkv', 'url': u'https://1fichier.com/?kpti0z', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'ID1': None, 'ID2': u'kpti0z', 'S': u'9.84', 'N': u'086 - Cars - Multi.mkv'}, 'size': 10565619548.16}
171	10.02.2015 15:05:53	DEBUG	OneFichierCom: Current file info: {'status': 2, 'name': u'086 - Cars - Multi.mkv', 'url': u'https://1fichier.com/?kpti0z', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'ID1': None, 'ID2': u'kpti0z', 'S': u'9.84', 'N': u'086 - Cars - Multi.mkv'}, 'size': 10565619548.16}
172	10.02.2015 15:05:53	DEBUG	OneFichierCom: File name: 086 - Cars - Multi.mkv | File size: 10565619548
173	10.02.2015 15:05:53	DEBUG	OneFichierCom: File status: online
174	10.02.2015 15:05:53	DEBUG	OneFichierCom: Handled as premium download
175	10.02.2015 15:05:55	DEBUG	Content-Disposition: 086 - Cars - Multi.mkv filename*=UTF-8086+-+Cars+-+Multi.mkv
176	10.02.2015 15:05:55	DEBUG	Chunked with range 3520965694-7041931388
177	10.02.2015 15:05:55	DEBUG	Chunked with range 7041931388-
```

**Comment by celena007** [comment]
Hello,

same file as olivv59 but no rename

229	10.02.2015 17:21:41	DEBUG	Redirected import module.plugins.hoster.OneFichierCom -> userplugins.hoster.OneFichierCom
230	10.02.2015 17:21:41	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
231	10.02.2015 17:21:41	INFO	Download starts: kpti0z
232	10.02.2015 17:21:41	DEBUG	OneFichierCom: Update file info...
233	10.02.2015 17:21:41	DEBUG	OneFichierCom: Previous file info: {}
234	10.02.2015 17:21:41	DEBUG	OneFichierCom: Current file info: {'status': 3, 'url': u'https://1fichier.com/?kpti0z', 'size': 0, 'name': u'kpti0z', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'kpti0z', 'ID1': None}}
235	10.02.2015 17:21:42	DEBUG	OneFichierCom: File name: kpti0z | File size: 10562897081
236	10.02.2015 17:21:42	DEBUG	OneFichierCom: File status: queued
237	10.02.2015 17:21:42	DEBUG	OneFichierCom: Looking for direct download link...
238	10.02.2015 17:21:42	DEBUG	OneFichierCom: Redirect #0 to: https://1fichier.com/?kpti0z
239	10.02.2015 17:21:42	DEBUG	OneFichierCom: Redirect #1 to: https://a-7.1fichier.com/c1080178402
240	10.02.2015 17:21:45	INFO	OneFichierCom: Direct download link detected
241	10.02.2015 17:21:48	DEBUG	Content-Disposition: 086 - Cars - Multi.mkv filename*=UTF-8086+-+Cars+-+Multi.mkv
242	10.02.2015 17:21:48	DEBUG	Chunked with range 3520965694-7041931388
243	10.02.2015 17:21:48	DEBUG	Chunked with range 7041931388-

**Comment by celena007** [comment]
I found the solution of my problem

In the 1fichier console i must check : Show the download menu
And the file is rename correctly on pyload

**Comment by yann19fr** [comment]
Works for me too !!!

**Comment by olivvv59** [comment]
I don`t find the option . where is the 1fichier console ?

**Comment by yann19fr** [comment]
In Parameters tabs, the third bloc : tic the checkbox

**Comment by olivvv59** [comment]
( Opps , I was looking for in  pyload .. not in 1fichier website :-D ) 

thanks !! 
It works for me too.

**Comment by olivvv59** [comment]
Good name but sometimes, i've this problem

```
"Downloaded content was smaller than expected. Try to reduce download connections"
```

I've got only 1 connection.

```
11.02.2015 13:02:30	DEBUG	OneFichierCom: Update file info...
22	11.02.2015 13:02:30	DEBUG	OneFichierCom: Previous file info: {}
23	11.02.2015 13:02:32	DEBUG	OneFichierCom: Current file info: {'status': 3, 'url': u'https://1fichier.com/?uxcvk5', 'size': 0, 'name': u'uxcvk5', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'uxcvk5', 'ID1': None}}
24	11.02.2015 13:02:32	DEBUG	OneFichierCom: File name: uxcvk5 | File size: Unknown
25	11.02.2015 13:02:32	DEBUG	OneFichierCom: File status: queued
26	11.02.2015 13:02:32	DEBUG	OneFichierCom: Looking for direct download link...
27	11.02.2015 13:02:32	DEBUG	OneFichierCom: Redirect #0 to: https://1fichier.com/?uxcvk5
28	11.02.2015 13:02:33	DEBUG	OneFichierCom: Direct download link not found
29	11.02.2015 13:02:34	DEBUG	OneFichierCom: Update file info...
30	11.02.2015 13:02:34	DEBUG	OneFichierCom: Previous file info: {'status': 3, 'url': u'https://1fichier.com/?uxcvk5', 'size': 0, 'name': u'uxcvk5', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'uxcvk5', 'ID1': None}}
31	11.02.2015 13:02:34	DEBUG	OneFichierCom: Current file info: {'status': 2, 'name': u'057 - Les Aventures de Tigrou - Multi.mkv', 'url': u'https://1fichier.com/?uxcvk5', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'ID1': None, 'ID2': u'uxcvk5', 'S': u'4.37', 'N': u'057 - Les Aventures de Tigrou - Multi.mkv'}, 'size': 4692251770.88}
32	11.02.2015 13:02:34	DEBUG	OneFichierCom: File name: 057 - Les Aventures de Tigrou - Multi.mkv | File size: 4692251770
33	11.02.2015 13:17:36	DEBUG	OneFichierCom: Update file info...
34	11.02.2015 13:17:36	DEBUG	OneFichierCom: Previous file info: {'status': 2, 'name': u'057 - Les Aventures de Tigrou - Multi.mkv', 'url': u'https://1fichier.com/?uxcvk5', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'ID1': None, 'ID2': u'uxcvk5', 'S': u'4.37', 'N': u'057 - Les Aventures de Tigrou - Multi.mkv'}, 'size': 4692251770.88}
11.02.2015 13:17:36	DEBUG	OneFichierCom: Current file info: {'status': 2, 'name': u'057 - Les Aventures de Tigrou - Multi.mkv', 'url': u'https://1fichier.com/?uxcvk5', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'ID1': None, 'ID2': u'uxcvk5', 'S': u'4.37', 'N': u'057 - Les Aventures de Tigrou - Multi.mkv'}, 'size': 4692251770.88}
36	11.02.2015 13:17:36	DEBUG	OneFichierCom: File name: 057 - Les Aventures de Tigrou - Multi.mkv | File size: 4692251770
37	11.02.2015 13:17:36	DEBUG	OneFichierCom: File status: online
38	11.02.2015 13:17:36	DEBUG	OneFichierCom: Handled as premium download
39	11.02.2015 13:17:38	DEBUG	Content-Disposition: 057 - Les Aventures de Tigrou - Multi.mkv filename*=UTF-8057+-+Les+Aventures+de+Tigrou+-+Multi.mkv
40	11.02.2015 13:17:38	DEBUG	Chunked with range 1564129351-3128258702
41	11.02.2015 13:17:38	DEBUG	Chunked with range 3128258702-
42	11.02.2015 14:28:42	WARNING	Download failed: 057 - Les Aventures de Tigrou - Multi.mkv | Downloaded content was smaller than expected. Try to reduce download connections.
43	11.02.2015 14:28:42	INFO	Debug Report written to debug_OneFichierCom_11-02-2015_14-28-42.zip
44	11.02.2015 14:28:42	ERROR	Error executing hooks: u'OneFichierCom'
```

**Comment by pilipi** [comment]
I have the same problem.

I tried all the propositions but nothing work... Do you have any news about it?

Thanks

**Comment by olivvv59** [comment]
With the download menu , it doesn t work anymore :-\ 
It downloads a HTML file

**Comment by vuolter** [comment]
@olivvv59 Sample url + python version + os name

**Comment by olivvv59** [comment]
* Python:	2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
* SMP Debian 3.2.63-2+deb7u1 i686

https://u1zg1fvszs.1fichier.com/ 

;-)

**Comment by vuolter** [comment]
Fixed in 0.4.10 .

**Comment by dedelastuce** [comment]
Hi all
I need to reopen this Issue because the problem comes again :
I download as Premium user on 1fichier and my file isnt renamed
When I download as free user everything is OK
I tried to check download menu in 1fichier website parameters but pyload download a small html file (but with the correct name !!!!!!)
 
My log with no rename / At the end the file calls ?07rmglbqf9 without any extension


18.01.2016 15:01:54	INFO	ADDON UpdateManager: pyLoad is up to date!
22	18.01.2016 15:01:55	INFO	ADDON UpdateManager: All plugins are up to date!
23	18.01.2016 15:02:16	INFO	Added package https://1fichier.com/?07rmglbqf9 containing 1 links
24	18.01.2016 15:02:16	INFO	Download starts: https://1fichier.com/?07rmglbqf9
25	18.01.2016 15:02:17	WARNING	HOSTER OneFichierCom[20]: Plugin may be unstable
26	18.01.2016 15:02:17	INFO	ACCOUNT OneFichierCom: Grabbing account info for user `antoine.aillot.01@gmail.com`...
27	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Grabbing link info...
28	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Link name: ?07rmglbqf9
29	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Link size: N/D
30	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Link status: en file d'attente
31	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Processing url: https://1fichier.com/?07rmglbqf9
32	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Looking for direct download link...
33	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Direct download link detected
34	18.01.2016 15:02:18	INFO	HOSTER OneFichierCom[20]: Downloading file...
35	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: File saved
36	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: Checking download...
37	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: File is OK
38	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: Checking file (with built-in rules)...
39	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: Checking file (with custom rules)...
40	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: Checking for link errors...
41	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: No errors found
42	18.01.2016 15:04:40	INFO	HOSTER OneFichierCom[20]: No errors found
43	18.01.2016 15:04:40	INFO	Download finished: ?07rmglbqf9
44	18.01.2016 15:04:40	INFO	Package finished: https://1fichier.com/?07rmglbqf9
