### ISSUE TITLE
ExternalScripts - Move downloads to different folders using Tags

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2336]
Given a specific download name, for example "DOC - Name_you_want", is it possible to automatically move it, after download completed, to a specific folder, in this example "Documents", so that you don't have only a folder ("Downloads" or what you set) with a lot of different files but different folders for different types of files?

Something like: if $ARG1 - Name_You_Want then, after download, move it to ARG1 folder.

I know it's not a common requested feature but it can be useful if you download a lot of different documents and you want to order these automatically.

**Comment by GammaC0de** [comment]
@Ryan747800B `pyLoad` has `ExternalScripts` plugin, just write a script to do what you want.

**Comment by Ryan747800B** [comment]
But how can I do a script that reads from download list? I don't know where to begin.

**Comment by GammaC0de** [comment]
pseudo code for the script:
if name contains 'TAG1' them move file to /documents

look at all the subfolders under /opt/etc/pyload/scripts, every script you put the will run on the specific event.
see https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExternalScripts.py for the arguments that is sent to every script

**Comment by Ryan747800B** [comment]
@GammaC0de Something like this (I found it so some things like scp commands aren't useful for me)

```
#!/bin/bash

cd "$/DataVolume/shares/Public/Downloads"
# for filename in *; do
find . -type f | while IFS= read filename; do # Look for files in all ~/Download sub-dirs
  case "${filename,,*}" in  # this syntax emits the value in lowercase: ${var,,*}  (bash version 4)
     *.part) : ;; # Excludes *.part files from being moved
     move.sh) : ;;
#    *TAG1*)            mv "$filename" "$/DataVolume/shares/Public/TAG1/" ;; # Using move there is no need to {&& rm "$filename"}
     *TAG2*)           scp "$filename" "USER@USER.local:/users/USER/TAG2/" && rm "$filename" ;;
     *TAG3A*TAG3B*)   scp "$filename" "USER@USER.local:/users/USER/TAG3/TAG3AB/" && rm "$filename" ;;
     *) echo "Don't know where to put $filename" ;;
  esac
done
```

Then I have only to put it to /scripts and then do a chmod +x?

**Comment by GammaC0de** [comment]
You put is under /scripts/<event_type> folder, where <event_type> is the event you want to act uppon - e.g: download_finished.

Currently, there is no way to specify priority, therefore I would solve this by either using just one script or by creating a script that calls the two others (obviously not located in  /scripts) one by one.

**Comment by Ryan747800B** [comment]
I didn't well understand this 

> where is the event you want to act uppon - e.g: download_finished.

If I do a script like this
```
#!/bin/bash#

bash <(curl -s https://URL_WHERE_I_SAVE_THE SCRIPT/Rename.sh)
bash <(curl -s https://URL_WHERE_I_SAVE_THE SCRIPT/Move.sh)
```
Where Rename.sh is
```
#!/bin/bash
#Here I'm still trying to make a working script that do
if there is a file "namefile.doc" in a folder "ARG1 - namefolder", then reads "namefolder" and rename "namefile" with this.
```


and Move.sh is
```
#!/bin/bash

cd "$/DataVolume/shares/Public/Downloads"
# for filename in *; do
find . -type f | while IFS= read filename; do # Look for files in all ~/Download sub-dirs
  case "${filename,,*}" in  # this syntax emits the value in lowercase: ${var,,*}  (bash version 4)
     *.part) : ;; # Excludes *.part files from being moved
     move.sh) : ;;
#    *TAG1*)            mv "$filename" "$/DataVolume/shares/Public/TAG1/" ;; # Using move there is no need to {&& rm "$filename"}
     *TAG2*)           scp "$filename" "USER@USER.local:/users/USER/TAG2/" && rm "$filename" ;;
     *TAG3A*TAG3B*)   scp "$filename" "USER@USER.local:/users/USER/TAG3/TAG3AB/" && rm "$filename" ;;
     *) echo "Don't know where to put $filename" ;;
  esac
done
```

and I put it to /scripts/ folder doing
```
cd /opt/etc/pyload/scripts
wget http://URL_WHERE_I_SAVE_THE SCRIPT/ExternalScript.sh
chmod +x ExtrnalScript.sh
```
Appending this at the end of [this](https://github.com/pyload/pyload/issues/2328#issuecomment-180789444) before `reboot` is correct?

**Comment by GammaC0de** [comment]
You put is under /scripts/\<event_type\> folder, where \<event_type\> is a subfolder reprsenting the event you want to act upon - e.g: download_finished.

Each script gets command line arguments:
```
#!/bin/sh
echo $1 $2 $3 $4 $5
```

**Comment by Ryan747800B** [comment]
Now I understand. So
```
mkdir /opt/etc/pyload/scripts/download_finished
cd /opt/etc/pyload/scripts/download_finished
wget http://URL_WHERE_I_SAVED_THE SCRIPT/ExternalScript.sh
chmod +x ExternalScript.sh
reboot
```

**Comment by vuolter** [comment]
@Ryan747800B Soon (hopefully) we will (re)open the wiki with all the needed documentation. :D

**Comment by GammaC0de** [comment]
@Ryan747800B Yes but better use `mkdir -p`

**Comment by Ryan747800B** [comment]
@GammaC0de Thank you I'll test it. P.S.: it's OT with this topic (unfortunately I closed that topic) but regarding pyLoad install script is there a way to complete the setup automatically (you know, set IP, port, name, etc.)?

**Comment by GammaC0de** [comment]
you could create /opt/etc/pyload/pyload.conf yourself so pyLoadCore -s is unneeded

Replace the "..." with the content of your /opt/etc/pyload/pyload.conf:
cat <<"EOM" >/opt/etc/pyload/pyload.conf
...
...
...
EOM

**Comment by Ryan747800B** [comment]
OK. I can simply add that to the end of the script

```
... etc

ln -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload

cat <<"EOM" >/opt/etc/pyload/pyload.conf
version: 1 

remote - "Remote":

... etc
... etc

downloadTime - "Download Time":
	time start : "Start" = 0:00
	time end : "End" = 0:00
EOM

reboot
```

**Comment by GammaC0de** [comment]
I guess so, you have to try it yourself to be sure

**Comment by Ryan747800B** [comment]
Thank you. I'll tell you if it works asap (lot of files copying now and I have no backup so I prefer wait until completed, you know :)

**Comment by GammaC0de** [comment]
@Ryan747800B No need for chmod, pyload.conf is a config file, not an executable/script

**Comment by Ryan747800B** [comment]
OK. However, after a quick look, I don't see parameters for username and password in pyload.conf. Probably they are contained (as hash, MD5?) in other files, I think.

**Comment by GammaC0de** [comment]
ah, yes, those are stored in files.db

**Comment by Ryan747800B** [comment]
@GammaC0de "files.db" appears to contain only download list. I don't see username or password parameters.

Regarding the installation script, I made some changes. Are they correctly written?

```
...
ln -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload

cat <<"EOM" >/opt/etc/pyload/pyload.conf
...
EOM

cat <<"EOM" >/opt/etc/pyload/files.db
#Here pyLoad username e password
EOM

mkdir -p /opt/etc/pyload/scripts/download_finished

cat <<"EOM" >/opt/etc/pyload/scripts/download_finished/ExternalScript.sh
sh /opt/etc/pyload/scripts/download_finished/SCRIPTS/Rename.sh
sleep 3
sh /opt/etc/pyload/scripts/download_finished/SCRIPTS/Move.sh
EOM

chmod +x /opt/etc/pyload/scripts/download_finished/ExternalScript.sh


mkdir -p /opt/etc/pyload/scripts/download_finished/SCRIPTS

cat <<"EOM" >/opt/etc/pyload/scripts/download_finished/SCRIPTS/Rename.sh
#Here script that given "TAG1 - Name" folder and "filename.doc" inside it, then "Name.doc"
EOM

chmod +x /opt/etc/pyload/scripts/download_finished/SCRIPTS/Rename.sh


cat <<"EOM" >/opt/etc/pyload/scripts/download_finished/SCRIPTS/Move.sh
#Here script that given "TAG1 - Name" folder and "TAG2 - OtherName" folders, then move "TAG1" to "/Public/Documents/TAG1" and "TAG2" to "/Public/Documents/TAG2"
EOM

chmod +x /opt/etc/pyload/scripts/download_finished/SCRIPTS/Move.sh


reboot
```

**Comment by GammaC0de** [comment]
Seems ok.
files.db is a sqlite database.
so, if you want to embed it in your script you could use base64 command to convert it from binary to text

**Comment by Ryan747800B** [comment]
Here it becomes really too complex. How can I do tis thing? I haven't got the slightest idea.

**Comment by GammaC0de** [comment]
to encode files.db into text: `bzip2 -9 -c  /opt/etc/pyload/files.db | base64`

then to decode it back in your script:
```
echo line1_from_result\
line2_from_result\
line3_from_result\
...
last_from_result | base64 -d | bzcat > /opt/etc/pyload/files.db
```

Another option is to save files.db somewhere and use wget.

**Comment by Ryan747800B** [comment]
If I do the second option, are there incompatibility issues from a installation to another (I don't know, some unique fingerprint inside or issues when upgrading, etc.)?

Because of now after I do `bzip2 -9 -c /opt/etc/pyload/files.db | base64 in Terminal` I have as output a very long string ending with ==; this length is because of there are downloads pending/completed? If i do first option, I have to simply copy/paste this to the script? I didn't well understand `line1_from_result\`; it means that I have to do

```
echo BWXTUUEmEKFpoxB3ECQM7603DBONrcjU9npuHWxYrGhu65vxPopNbtcJk3HPU5i5taz5xn6zkMVl
...
BWXTUUEmEKFpoxB3ECQM7603DBONrcjU9npuHWxYrGhu65vxPopNbtcJk3HPU5i5taz5xn6zkMVl | base64 -d | bzcat > /opt/etc/pyload/files.db
```

**Comment by GammaC0de** [comment]
You add \\ at the end of every line except the last:
```
echo BWXTUUEmEKFpoxB3ECQM7603DBONrcjU9npuHWxYrGhu65vxPopNbtcJk3HPU5i5taz5xn6zkMVl\
BWXTUUEmEKFpoxB3ECQM7603DBONrcjU9npuHWxYrGhu65vxPopNbtcJk3HPU5i5taz5xn6zkMVl\
BWXTUUEmEKFpoxB3ECQM7603DBONrcjU9npuHWxYrGhu65vxPopNbtcJk3HPU5i5taz5xn6zkMVl\
...
...
BWXTUUEmEKFpoxB3ECQM7603DBONrcjU9npuHWxYrGhu65vxPopNbtcJk3HPU5i5taz5xn6zkMVl | base64 -d | bzcat > /opt/etc/pyload/files.db

**Comment by Ryan747800B** [comment]
@GammaC0de This is the new code about payload.conf and files.db but Terminal output gives me some errors

l```
n -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload
# End of pyLoad Install - payload

# pyLoad Install - pyload.conf
cat <<"EOM" >/opt/etc/pyload/pyload.conf
version: 1 

remote - "Remote":
...
downloadTime - "Download Time":
	time start : "Start" = 0:00
	time end : "End" = 0:00
EOM
# End of pyLoad Install - pyload.conf

# pyLoad Install - files.db
cat <<"EOM" >/opt/etc/pyload/files.db
echo fist_line_string\
...\
...\
...\
last_line_string | base64 -d | bzcat > /opt/etc/pyload/files.db
EOM
# End of pyLoad Install - files.db
```

And this is the Terminal output

```
/dev/fd/61: line 135: /opt/etc/pyload/pyload.conf: No such file or directory
/dev/fd/61: line 214: /opt/etc/pyload/files.db: No such file or directory
```

Line 135 and 214 correspond respectively `cat <<"EOM" >/opt/etc/pyload/pyload.conf` and `cat <<"EOM" >/opt/etc/pyload/files.db`

Why "No such file or directory" if I create it with `cat`?

**Comment by GammaC0de** [comment]
@Ryan747800B 
```
ln -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload
# End of pyLoad Install - pyLoad

# pyLoad Install - pyload.conf
cat <<"EOM" >/opt/etc/pyload/pyload.conf
version: 1 

remote - "Remote":
...
downloadTime - "Download Time":
    time start : "Start" = 0:00
    time end : "End" = 0:00
EOM
# End of pyLoad Install - pyload.conf

# pyLoad Install - files.db
echo fist_line_string\
...\
...\
...\
last_line_string | base64 -d | bzcat > /opt/etc/pyload/files.db
# End of pyLoad Install - files.db
```

**Comment by Ryan747800B** [comment]
@GammaC0de Same output error: it's strange because of I checked if `/opt/etc/pyload` folder exists and it's OK. In fact if I do this `/opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -s` it works, so no installation/script error. I'm not sure, but a solution can be to pipe the input.

`{ echo en ; echo enter ; echo enter ; echo yes ; echo ... ; } | /opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -s`

**Comment by GammaC0de** [comment]
:+1: Also, much simpler solution..

**Comment by Ryan747800B** [comment]
Only a question: but is it possible to pipe not a word but a "enter"?

**Comment by GammaC0de** [comment]
@Ryan747800B echo automatically adds enter at the end so "echo enter" should be actually "echo"

**Comment by Ryan747800B** [comment]
Well the idea is good but it doesn't works completely

Here is the example string

`{ echo en ; echo ; echo ; echo s ; echo n ; echo s ; echo username ; echo password ; echo password ; echo n ; echo en ; echo /DataVolume/shares/Public ; echo 3 ; echo s ; echo n ; echo n ; echo s ; echo nN.nN.nN.nN ; echo nNnn ; echo threaded ; } | /opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -s`

And here the output

```
The following logindata is valid for CLI, GUI and web interface
Username [User]: Traceback (most recent call last):
  File "/opt/bin/pyLoadCore", line 667, in <module>
    main()
  File "/opt/bin/pyLoadCore", line 656, in main
    pyload_core = Core()
  File "/opt/bin/pyLoadCore", line 114, in __init__
    s.start()
  File "/opt/share/pyload/module/setup.py", line 167, in start
    self.conf_basic()
  File "/opt/share/pyload/module/setup.py", line 280, in con_basic
    password = self.ask("", "", password=True)
  File "/opt/share/pyload/module/setup.py", line 468, in ask
    p1 = getpass(qst.encode("utf-8"))
  File "/opt/lib/python2.5/getpass.py", line 32, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (22, 'Invalid argument')
```.

Where am I doing wrong?

**Comment by GammaC0de** [comment]
Unfortunately, setup uses `getpass` function for getting the password so piping to stdin will not work..
So your option would either go back to the previous method or to skip the user setup and adding it via SQL command:
`sqlite3 /opt/etc/pyload/files.db "INSERT INTO "users" VALUES(1,'username','','abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef',0,0,'default');"`

You can see the content of the users table via:
`sqlite3 /opt/etc/pyload/files.db ".dump users"`

**Comment by Ryan747800B** [comment]
@GammaC0de Sorry but busy week! However there are four methods:

1. Using `cat`
```
/dev/fd/61: line 135: /opt/etc/pyload/pyload.conf: No such file or directory
/dev/fd/61: line 214: /opt/etc/pyload/files.db: No such file or directory
```

2. Using `wget`
If i add a download to queue, it doesn't start. I tried everything (rebooting, checking setting)

3. Using `cat+rename`
```
cat <<"EOM" >/opt/etc/pyload/pyload.txt
...
EOM

mv /opt/etc/pyload/pyload.txt /opt/etc/pyload/pyload.conf
```

4. Using `cat` or `wget` or `cat+rename` and `sqlite`

Every method has some errors or doesn't work properly. How can I solve it?

**Comment by Ryan747800B** [comment]
Update: I tried to do all commands manually and I figured out that the problem is probably with the script but I don't know why.

Here the commands - manually

```
MyBookLive:~# cat <<"EOM" >/opt/etc/pyload/pyload.conf
> version: 1 
> 
> remote - "Remote":
...
> time end : "End" = 0:00
> EOM
```

```
MyBookLive:~# sqlite3 /opt/etc/pyload/files.db "INSERT INTO "users" VALUES(1,'username','','ababababpasswordababab',0,0,'default');"
Error: no such table: users
```

```
echo ababababababababba\
> abababababababbaabab\
...
> abababb= | base64 -d | bzcat > /opt/etc/pyload/files.db
```

And here the script

```
cat <<"EOM" >/opt/etc/pyload/pyload.conf
version: 1 

remote - "Remote":
...
        time end : "End" = 0:00
EOM
```

```
echo ababababababababba\
...
abababb = | base64 -d | bzcat > /opt/etc/pyload/files.db
```

**Comment by GammaC0de** [comment]
```
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "email" TEXT DEFAULT "" NOT NULL, "password" TEXT NOT NULL, "role" INTEGER DEFAULT 0 NOT NULL, "permission" INTEGER DEFAULT 0 NOT NULL, "template" TEXT DEFAULT "default" NOT NULL)'
sqlite3 /opt/etc/pyload/files.db "INSERT INTO "users" VALUES(1,'username','','ababababpasswordababab',0,0,'default');"

**Comment by Ryan747800B** [comment]
And what about `cat <<"EOM" >/opt/etc/pyload/pyload.conf` ?

**Comment by GammaC0de** [comment]
what about it?

**Comment by Ryan747800B** [comment]
If I do that command with the installscript it says
`/dev/fd/62: line 143: /opt/etc/pyload/pyload.conf: No such file or directory`

But if I do it manually
`cat <<"EOM" >/opt/etc/pyload/pyload.conf`

it works

**Comment by GammaC0de** [comment]
Try maybe `mkdir -p /opt/etc/pyload` before cat

**Comment by Ryan747800B** [comment]
OK I try now

**Comment by Ryan747800B** [comment]
Script
```
chmod +x /opt/etc/init.d/pyload
ln -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload
# End of pyLoad Install - pyLoad

# pyLoad Install - files.db
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "email" TEXT DEFAULT "" NOT NULL, "password" TEXT NOT NULL, "role" INTEGER DEFAULT 0 NOT NULL, "permission" INTEGER DEFAULT 0 NOT NULL, "template" TEXT DEFAULT "default" NOT NULL)'
sqlite3 /opt/etc/pyload/files.db "INSERT INTO "users" VALUES(1,'username','','password',0,0,'default');"
chmod 0600 files.db
# End of pyLoad Install - files.db

# pyLoad Install - pyload.conf
mkdir -p /opt/etc/pyload
cat <<"EOM" >/opt/etc/pyload/pyload.conf
version: 1 

remote - "Remote":
...
time end : "End" = 0:00
EOM
# End of pyLoad Install - pyload.conf
```

Terminal output
```
2016-02-20 07:52:42 (158 MB/s) - `./UpdateManager.py' saved [6908/6908]

Error: unable to open database "/opt/etc/pyload/files.db": unable to open database file
Error: unable to open database "/opt/etc/pyload/files.db": unable to open database file
chmod: cannot access `files.db': No such file or directory
```

pyLoad.conf seems OK; files.db not

**Comment by GammaC0de** [comment]
```
chmod +x /opt/etc/init.d/pyload
ln -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload
# End of pyLoad Install - pyLoad

# pyLoad Install - pyload.conf
mkdir -p /opt/etc/pyload
chmod 777 /opt/etc/pyload
cat <<"EOM" >/opt/etc/pyload/pyload.conf
version: 1 

remote - "Remote":
...
time end : "End" = 0:00
EOM
# End of pyLoad Install - pyload.conf

# pyLoad Install - files.db
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "email" TEXT DEFAULT "" NOT NULL, "password" TEXT NOT NULL, "role" INTEGER DEFAULT 0 NOT NULL, "permission" INTEGER DEFAULT 0 NOT NULL, "template" TEXT DEFAULT "default" NOT NULL)'
sqlite3 /opt/etc/pyload/files.db "INSERT INTO "users" VALUES(1,'username','','password',0,0,'default');"
chmod 0600 files.db
# End of pyLoad Install - files.db
```

First pyload.conf then files.db
notice the `chmod 777 /opt/etc/pyload` after mkdir

**Comment by Ryan747800B** [comment]
Same error `chmod: cannot access `files.db': No such file or directory` but probably I know why

```
# pyLoad Install - files.db
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "email" TEXT DEFAULT "" NOT NULL, "password" TEXT NOT NULL, "role" INTEGER DEFAULT 0 NOT NULL, "permission" INTEGER DEFAULT 0 NOT NULL, "template" TEXT DEFAULT "default" NOT NULL)'
sqlite3 /opt/etc/pyload/files.db "INSERT INTO "users" VALUES(1,'username','','password',0,0,'default');"
chmod 0600 files.db
# End of pyLoad Install - files.db
```

to

`chmod 0600 /opt/etc/pyload/files.db`

**Comment by GammaC0de** [comment]
yep

**Comment by Ryan747800B** [comment]
Testing right now...

**Comment by Ryan747800B** [comment]
It works!!! It just works! Thank you very much!!! I only suggest to add
```
opt/etc/init.d/pyload restart
sleep 120
```
right before reboot so only one reboot instead of reboot/wait for plugins update/reboot.

**Comment by GammaC0de** [comment]
:+1: :+1: :+1: 

Use this instead of sleep:
```
marks=( '/' '-' '\' '|' )

while [[ 1 ]]; do
	/opt/etc/init.d/pyload restart
	i=0
	tail -f /opt/etc/Logs/log.txt | while read LOGLINE
	do
		printf "\rpyLoad updating, please wait ... ${marks[i++ % ${#marks[@]}]}"
		sleep 0.1
		[[ "${LOGLINE}" == *"please restart pyLoad"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; break)
		[[ "${LOGLINE}" == *"All plugins are up to date"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; reboot)
	done
done
```

**Comment by Ryan747800B** [comment]
Thank you. I try it.

**Comment by vuolter** [comment]
Mmmhn... TagFolder... Not a so bad name for an addon... mmmhn.

**Comment by Ryan747800B** [comment]
@vuolter Good name! "TagFolder: from now you will not have to worry about sorting your downloads. It's all automatic."

**Comment by Ryan747800B** [comment]
A question: is it possible to do a combination of mkdir -p and chmod -m?
Instead of

```
#check if exists, then create
mkdir -p /DataVolume/shares/Public/Folder
#only if created, set permission
chmod 775 /DataVolume/shares/Public/Folder
```

**Comment by GammaC0de** [comment]
To check if a directory exists in a shell script you can use the following:
```bash
if [ -d "$DIRECTORY" ]; then
  # Control will enter here if $DIRECTORY exists.
fi
```

Or to check if a directory doesn't exist:
```bash
if [ ! -d "$DIRECTORY" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
fi
```

**Comment by Ryan747800B** [comment]
@GammaC0de OK, now i test it!

**Comment by Ryan747800B** [comment]
Loop mode

```
Starting pyload download manager daemon: payload
tail: cannot open `/opt/etc/Logs/log.txt' for reading: No such file or directory
tail: no files remaining
```.

**Comment by GammaC0de** [comment]
It should be `/opt/etc/pyload/Logs/log.txt`

**Comment by Ryan747800B** [comment]
@GammaC0de It hangs here

```
Stopping pyload download manager daemon: payload
Starting pyload download manager daemon: payload
pyLoad updating, please wait ... Done.
Stopping pyload download manager daemon: payload
Starting pyload download manager daemon: payload
pyLoad updating, please wait ... -
```

**Comment by Ryan747800B** [comment]
Another strange things is that if I run the script and do files.db and pyload.conf automatically, if I try to download something it doesn't start (queue); but if I run the same script but with manual setup it works. Is strange because of files.db content and pyload.conf content are exactly the same. What do you think about it?

**Comment by GammaC0de** [comment]
@Ryan747800B Are you sure it hangs? When I check it, the update took 3-5 minutes.
you can monitor to update process if you open a second putty session and type `tail -f /opt/etc/pyload/Logs/log.txt`


As for files.db, add these lines too:
```
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "packages" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "folder" TEXT, "password" TEXT DEFAULT "", "site" TEXT DEFAULT "", "queue" INTEGER DEFAULT 0 NOT NULL, "packageorder" INTEGER DEFAULT 0 NOT NULL)'
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "links" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "url" TEXT NOT NULL, "name" TEXT, "size" INTEGER DEFAULT 0 NOT NULL, "status" INTEGER DEFAULT 3 NOT NULL, "plugin" TEXT DEFAULT "BasePlugin" NOT NULL, "error" TEXT DEFAULT "", "linkorder" INTEGER DEFAULT 0 NOT NULL, "package" INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY(package) REFERENCES packages(id))'
sqlite3 /opt/etc/pyload/files.db 'CREATE INDEX IF NOT EXISTS "pIdIndex" ON links(package)'
sqlite3 /opt/etc/pyload/files.db 'CREATE TABLE IF NOT EXISTS "storage" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "identifier" TEXT NOT NULL, "key" TEXT NOT NULL, "value" TEXT DEFAULT "")'
```

**Comment by Ryan747800B** [comment]
Yes I'm sure. All these test are done with fresh firmware install to prevent issues. Here logs:

```
MyBookLive:~# tail -f /opt/etc/pyload/Logs/log.txt
21.02.2016 09:06:46 INFO      UpdateManager: New version of account|QuickshareCz : 0.09
...
21.02.2016 09:09:32 INFO      UpdateManager: *** Plugins have been updated, please restart pyLoad ***
21.02.2016 09:09:33 INFO      shutting down...
21.02.2016 09:09:33 INFO      Received Quit signal
...
21.02.2016 09:09:41 INFO      Starting threaded webserver: 0.0.0.0:9090
```

And stops here

**Comment by GammaC0de** [comment]
Ok, change it to:
```
marks=( '/' '-' '\' '|' )

/opt/etc/init.d/pyload start
i=0
tail -f /opt/etc/Logs/log.txt | while read LOGLINE
do
    printf "\rpyLoad updating, please wait ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"please restart pyLoad"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; reboot)
done
```

**Comment by Ryan747800B** [comment]
Doing... I changed the line /opt/... because of

```
tail: cannot open `/opt/etc/Logs/log.txt' for reading: No such file or directory
tail: no files remaining
```
to

```
marks=( '/' '-' '\' '|' )

/opt/etc/init.d/pyload start
i=0
tail -f /opt/etc/pyload/Logs/log.txt | while read LOGLINE
do
    printf "\rpyLoad updating, please wait ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"please restart pyLoad"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; reboot)
done
```

Regarding queue issus I test it after reboot

**Comment by GammaC0de** [comment]
:+1:

**Comment by Ryan747800B** [comment]
Done! Plugins have been updated correctly. Downloads still not working.

**Comment by GammaC0de** [comment]
Run it in debug mode and see if you see something useful.

**Comment by Ryan747800B** [comment]
Nothing strange

```
MyBookLive:~# /opt/etc/init.d/pyload stop
Stopping pyload download manager daemon: payload
MyBookLive:~# /opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -d
21.02.2016 10:59:32 INFO      Starting payload 0.4.9
21.02.2016 10:59:32 INFO      Using home directory: /opt/etc/pyload
21.02.2016 10:59:32 DEBUG     Remote activated: False
21.02.2016 10:59:35 DEBUG     created index of plugins
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.internal.misc -> userplugins.internal.misc
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
21.02.2016 10:59:35 INFO      ADDON ExternalScripts: Activated scripts in folder `download_finished`: ExternalScript.sh
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.hooks.AntiStandby -> userplugins.hooks.AntiStandby
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
21.02.2016 10:59:35 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
21.02.2016 10:59:36 DEBUG     Redirected import module.plugins.hooks.XFileSharing -> userplugins.hooks.XFileSharing
21.02.2016 10:59:36 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
21.02.2016 10:59:36 DEBUG     Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
21.02.2016 10:59:36 INFO      Activated plugins: AntiStandby, CaptchaTrader, ClickAndLoad, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
21.02.2016 10:59:36 INFO      Deactivate plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, Ev0InFetcher, ExpertDecoders, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, MultishareCz, PushBullet, PushOver, RealdebridCom, RehostTo, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP, XMPPInterface
21.02.2016 10:59:36 INFO      Downloadtime: True
21.02.2016 10:59:36 INFO      Free space: 1.62 TiB
21.02.2016 10:59:36 INFO      Activating Accounts...
21.02.2016 10:59:36 INFO      Activating Plugins...
21.02.2016 10:59:36 INFO      Starting threaded webserver: 0.0.0.0:8000
21.02.2016 10:59:36 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
```.

**Comment by GammaC0de** [comment]
Start a download in debug mode and post the log

**Comment by Ryan747800B** [comment]
**21.02.2016 11:18:16 INFO      Added package TEST containing 1 links
21.02.2016 11:18:16 DEBUG     Redirected import module.plugins.hoster.BasePlugin -> userplugins.hoster.BasePlugin
21.02.2016 11:18:16 DEBUG     Redirected import module.plugins.hoster.Http -> userplugins.hoster.Http
21.02.2016 11:18:16 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
21.02.2016 11:18:16 DEBUG     Redirected import module.plugins.internal.Base -> userplugins.internal.Base
21.02.2016 11:18:16 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha**

Here the test link `http://cdimage.kali.org/kali-2016.1/kali-linux-2016.1-amd64.iso`

**Comment by GammaC0de** [comment]
That's all?

**Comment by Ryan747800B** [comment]
Yes

**Comment by GammaC0de** [comment]
backup `files.db`, delete it, then run setup normally and try downloading, see if works.

**Comment by Ryan747800B** [comment]
Deleted `files.db`, run setup (in this way it also clears pyload.conf?), restarted pyLoad, re-tried to add a download: don't works.

```
MyBookLive:~#  /opt/etc/init.d/pyload restart
Stopping pyload download manager daemon: pyload
Starting pyload download manager daemon: pyload
```

Restarted NAS: don't works; again queued

```
MyBookLive:~#  /opt/etc/init.d/pyload restart
Stopping pyload download manager daemon: pyload
Starting pyload download manager daemon: pyload
MyBookLive:~# reboot
```

So, if I do only a manual setup, it works; if I create db and conf it doesn't work; if I delete only db file, do a reboot and then run a setup, it doesn't works. But if pyload.conf files auto-created and manual-created are the same (I checked), where's the problem? :confused:

**Comment by GammaC0de** [comment]
So it doesn't work either way?

**Comment by Ryan747800B** [comment]
Yes; in fact if instead of doing these two methods (script and manual) I do a wget of db and conf files backed up from a "pure" manual setup, it doesn't work either. So, it could be that:
1. Not only files.db and pyload.conf are involved
2. There's some unique installation fingerprint in these two files

**Comment by Ryan747800B** [comment]
@vuolter Doing pyLoad setup manually which files are involved, only files.db and pyload.conf? I'm looking for documentation on pyLoad but the site is unreachable.

**Comment by GammaC0de** [comment]
@Ryan747800B Does is work with "manual setup"?

**Comment by Ryan747800B** [comment]
Yes, with `/opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -s` it works fine. But doing wget of the exact same files made with that manual setup or doing cat+echo it doesn't work. And all three times NAS firmware was freshly reinstalled.

**Comment by Ryan747800B** [comment]
Tried to add `mkdir -p -m 755 /DataVolume/shares/Public/Downloads` right before pyLoad reboot/update (so that it doesn't create it using conf file) but it doesn't work again. I'm trying to analyze all the variables to find the problem.

**Comment by GammaC0de** [comment]
Can you check if the file `/opt/share/pyload/module/config/configdir` exists?

**Comment by Ryan747800B** [comment]
Checked now: it doesn't exists!

**Comment by Ryan747800B** [comment]
There are 3 files configdir, default.cof and gui_default.xml; no folder.

**Comment by GammaC0de** [comment]
Are downloads "on"?

![untitled](https://cloud.githubusercontent.com/assets/11036551/13263363/e322d65e-da71-11e5-9c4b-ec9938752816.PNG)

**Comment by Ryan747800B** [comment]
Yes, yes of course. You have no way to test the script on a spare NAS?

**Comment by Ryan747800B** [comment]
@GammaC0de Update: I tried to replace the not-working folder `/opt/etc/pyload`(created with the script) with the working one (/opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -s): It doesn't work either. At this point it is clear that there is something which prevents operation.

**Comment by GammaC0de** [comment]
@Ryan747800B I tested the script and had this issue too.
I had it even without the script i.e. "manual" install.

Apparently, the problem relies in `plugins.conf`: If you get `plugins.conf` form a working setup, everything works fine...

I don't know what in `plugins.conf` causes it yet

**Comment by Ryan747800B** [comment]
@GammaC0de I tried now to do a "manual" installation and it works fine. It's really strange that even with manal setup you have issues.

**Comment by Ryan747800B** [comment]
I found where the problem can be: as I said, a manual install works fine BUT after few minutes it asked me to reboot to update plugins (obviously, because of I commented out the update script). Well, now it doesn't work. So the problem is about updated plugins: if you update it doesn't work, but if you don't update you have an outdated installation.

**Comment by Ryan747800B** [comment]
@GammaC0de Sorry if I ask you but have you tried to compare the two files? You're saying that a pyload.conf saved from an old working installation is fine; maybe a wrong files permission? Or maybe the Download folder has wrong permission (I can't access from Finder, but I create a new one it doesn't work too).

**Comment by GammaC0de** [comment]
@Ryan747800B not `pyload.conf` but `plugin.conf`

**Comment by GammaC0de** [comment]
@Ryan747800B I think I found the cause of this problem:
Edit `plugin.conf`:
* Find the "AntiStandby" section
* Change the "Activated" form `True` to `False`
* Save the file

Please update if this helps.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/2d19091e8decf310891246e0220a2ae46dff1aa9 Should be fixed now, please retry

**Comment by Ryan747800B** [comment]
@GammaC0de Sorry for late reply. Unfortunately still not working. I did a clean install, so that it downloads new version of `plugin.con`, so there are no doubts. Here the new `plugin.con`:

```
AntiStandby - "AntiStandby":
	int interval : "HDD touching interval in seconds" = 25
	bool activated : "Activated" = False
	bool system : "Prevent OS standby" = True
	bool hdd : "Prevent HDD standby" = True
	bool display : "Prevent display standby" = False
```

**Comment by GammaC0de** [comment]
So now its working?

![untitled](https://cloud.githubusercontent.com/assets/11036551/13380976/5a62d4a0-de58-11e5-8a2e-8311a69dc5b2.PNG)

**Comment by Ryan747800B** [comment]
No, unfortunately not.

**Comment by GammaC0de** [comment]
Try editing `plugin.conf` and disable all hook plugins beside `UpdateManager` and `ClickNLoad` then start in debug mode and watch the log

**Comment by Ryan747800B** [comment]
Disabling all plugins besides UpdateManager and CliickNLoad works fine. Here the output (There are 3 TEST files - before update, after update and after disabling)

```
MyBookLive:~# /opt/etc/init.d/pyload stop
Stopping pyload download manager daemon: payload
MyBookLive:~# /opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -d
29.02.2016 00:00:16 INFO      Starting payload 0.4.9
29.02.2016 00:00:16 INFO      Using home directory: /opt/etc/pyload
29.02.2016 00:00:16 DEBUG     Remote activated: False
29.02.2016 00:00:19 DEBUG     created index of plugins
29.02.2016 00:00:19 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
29.02.2016 00:00:20 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
29.02.2016 00:00:20 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
29.02.2016 00:00:20 DEBUG     Redirected import module.plugins.internal.misc -> userplugins.internal.misc
29.02.2016 00:00:20 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
29.02.2016 00:00:20 INFO      Activated plugins: ClickNLoad, UpdateManager
29.02.2016 00:00:20 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, CaptchaTrader, Checksum, ClickAndLoad, DeathByCaptcha, DeleteFinished, DownloadScheduler, Ev0InFetcher, EventMapper, ExpertDecoders, ExternalScripts, ExtractArchive, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, MultishareCz, PushBullet, PushOver, RealdebridCom, RehostTo, RestartFailed, SkipRev, TransmissionRPC, UnSkipOnFail, UserAgentSwitcher, WindowsPhoneNotify, XFileSharing, XMPP, XMPPInterface
29.02.2016 00:00:20 INFO      Downloadtime: True
29.02.2016 00:00:20 INFO      Free space: 1.57 TiB
29.02.2016 00:00:20 INFO      Activating Accounts...
29.02.2016 00:00:20 INFO      Activating Plugins...
29.02.2016 00:00:21 INFO      Starting threaded webserver: 0.0.0.0:8000
29.02.2016 00:00:21 INFO      pyLoad is up and running
29.02.2016 00:00:21 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | just_header=False | post={} | ref=True | multipart=False
29.02.2016 00:00:22 INFO      ADDON UpdateManager: pyLoad is up to date!
29.02.2016 00:00:22 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | just_header=False | post={} | ref=True | multipart=False
29.02.2016 00:00:22 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS ShareRapidCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CRYPTER ShareRapidComFolder
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CRYPTER YoutubeBatch
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CRYPTER HotfileFolderCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CONTAINER LinkList
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS CaptchaTrader
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS ClickAndLoad
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOSTER ShareRapidCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS UploadingCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS RehostTo
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CONTAINER DLC_25
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS HotfileCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS NetloadIn
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CRYPTER OneKhDe
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: INTERNAL AbstractExtractor
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOSTER RapidshareCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS RapidshareCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS MultishareCz
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS XMPPInterface
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CONTAINER DLC_26
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS IRCInterface
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS RealdebridCom
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CONTAINER DLC_27
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: CAPTCHA captcha
29.02.2016 00:00:22 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS Ev0InFetcher
29.02.2016 00:00:22 INFO      ADDON UpdateManager: New version of plugin: CAPTCHA ReCaptcha (v0.24 -> v0.25)
29.02.2016 00:00:22 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/c40dcf3/module/plugins/captcha/ReCaptcha.py | redirect=True | decode=False | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x106cddc0> | just_header=False | post={} | ref=True | multipart=False
29.02.2016 00:00:22 INFO      ADDON UpdateManager: New version of plugin: HOSTER FilejokerNet (v0.01 -> v0.02)
29.02.2016 00:00:22 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/b03d3c3/module/plugins/hoster/FilejokerNet.py | redirect=True | decode=False | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x106cddc0> | just_header=False | post={} | ref=True | multipart=False
29.02.2016 00:00:22 INFO      ADDON UpdateManager: *** Plugins updated ***
29.02.2016 00:00:22 DEBUG     Request reload of plugins: [(u'captcha', u'ReCaptcha'), (u'hoster', u'FilejokerNet')]
29.02.2016 00:00:23 DEBUG     Redirected import module.plugins.hoster.BasePlugin -> userplugins.hoster.BasePlugin
29.02.2016 00:00:23 DEBUG     Redirected import module.plugins.hoster.Http -> userplugins.hoster.Http
29.02.2016 00:00:23 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
29.02.2016 00:00:23 DEBUG     Redirected import module.plugins.internal.Base -> userplugins.internal.Base
29.02.2016 00:00:23 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
29.02.2016 00:00:23 INFO      Download starts: http://ovh.net/files/1Mb.dat
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: Plugin version: 0.51
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: Plugin status: testing
29.02.2016 00:00:23 WARNING   HOSTER BasePlugin[2]: Plugin may be unstable
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: Config option `use_premium` not found, use default `True`
29.02.2016 00:00:23 INFO      HOSTER BasePlugin[2]: Grabbing link info...
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: Link info: {'status': 7, 'hash': {}, 'name': '1Mb.dat', 'url': u'http://ovh.net/files/1Mb.dat', 'pattern': {}, 'size': 0}
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: Previous link info: {}
29.02.2016 00:00:23 INFO      HOSTER BasePlugin[2]: Link name: 1Mb.dat
29.02.2016 00:00:23 INFO      HOSTER BasePlugin[2]: Link size: N/D
29.02.2016 00:00:23 INFO      HOSTER BasePlugin[2]: Link status: starting
29.02.2016 00:00:23 INFO      HOSTER BasePlugin[2]: Processing url: http://ovh.net/files/1Mb.dat
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: LOAD URL http://ovh.net/files/1Mb.dat | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=True | post={} | ref=True | multipart=False
29.02.2016 00:00:23 DEBUG     HOSTER BasePlugin[2]: DOWNLOAD URL http://ovh.net/files/1Mb.dat | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
29.02.2016 00:00:23 DEBUG     Chunked with range 41667-83334
29.02.2016 00:00:23 DEBUG     Chunked with range 83334-
29.02.2016 00:00:24 INFO      HOSTER BasePlugin[2]: File saved
29.02.2016 00:00:24 INFO      HOSTER BasePlugin[2]: Checking download...
29.02.2016 00:00:24 INFO      HOSTER BasePlugin[2]: File is OK
29.02.2016 00:00:24 INFO      Download finished: 1Mb.dat
29.02.2016 00:00:24 INFO      Package finished: TEST2
29.02.2016 00:00:24 DEBUG     All downloads processed
29.02.2016 00:00:24 DEBUG     All downloads finished
29.02.2016 00:00:27 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
29.02.2016 00:00:27 ERROR     ADDON ClickNLoad: (98, 'Address already in use')
Traceback (most recent call last):
  File "/opt/lib/python2.5/threading.py", line 462, in __bootstrap
    self.__bootstrap_inner()
  File "/opt/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/etc/pyload/userplugins/hooks/ClickNLoad.py", line 103, in _server
    dock_socket.bind((self.cnl_ip, self.cnl_port))
  File "<string>", line 1, in bind
error: (98, 'Address already in use')

29.02.2016 00:00:49 INFO      Added package TEST3 containing 1 links
29.02.2016 00:00:49 INFO      Download starts: http://ovh.net/files/1Gb.dat
29.02.2016 00:00:49 DEBUG     HOSTER BasePlugin[3]: Plugin version: 0.51
29.02.2016 00:00:49 DEBUG     HOSTER BasePlugin[3]: Plugin status: testing
29.02.2016 00:00:49 WARNING   HOSTER BasePlugin[3]: Plugin may be unstable
29.02.2016 00:00:49 DEBUG     HOSTER BasePlugin[3]: Config option `use_premium` not found, use default `True`
29.02.2016 00:00:49 INFO      HOSTER BasePlugin[3]: Grabbing link info...
29.02.2016 00:00:49 DEBUG     HOSTER BasePlugin[3]: Link info: {'status': 7, 'hash': {}, 'name': '1Gb.dat', 'url': u'http://ovh.net/files/1Gb.dat', 'pattern': {}, 'size': 0}
29.02.2016 00:00:49 DEBUG     HOSTER BasePlugin[3]: Previous link info: {}
29.02.2016 00:00:49 INFO      HOSTER BasePlugin[3]: Link name: 1Gb.dat
29.02.2016 00:00:49 INFO      HOSTER BasePlugin[3]: Link size: N/D
29.02.2016 00:00:49 INFO      HOSTER BasePlugin[3]: Link status: starting
29.02.2016 00:00:49 INFO      HOSTER BasePlugin[3]: Processing url: http://ovh.net/files/1Gb.dat
29.02.2016 00:00:49 DEBUG     HOSTER BasePlugin[3]: LOAD URL http://ovh.net/files/1Gb.dat | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=True | post={} | ref=True | multipart=False
29.02.2016 00:00:52 DEBUG     HOSTER BasePlugin[3]: DOWNLOAD URL http://ovh.net/files/1Gb.dat | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
29.02.2016 00:00:52 DEBUG     Chunked with range 41666667-83333334
29.02.2016 00:00:52 DEBUG     Chunked with range 83333334-
29.02.2016 00:01:08 INFO      HOSTER BasePlugin[3]: File saved
29.02.2016 00:01:09 INFO      HOSTER BasePlugin[3]: Checking download...
29.02.2016 00:01:09 INFO      HOSTER BasePlugin[3]: File is OK
29.02.2016 00:01:09 INFO      Download finished: 1Gb.dat
29.02.2016 00:01:09 INFO      Package finished: TEST3
29.02.2016 00:01:09 DEBUG     All downloads processed
29.02.2016 00:01:09 DEBUG     All downloads finished
```.

**Comment by GammaC0de** [comment]
OK, that's good news, it means that your script works fine and the problem is in one of the hook plugins.

Try enabling the plugins one by one and see which plugin is the problematic one.

**Comment by Ryan747800B** [comment]
There are a lot of plugins :tired_face:
Tried right now to disable all plugins below UpdateManager, so from line 931 - MultiUpOrg to last line 1733 and it doesn't works; Now I try with the remaining.

**Comment by GammaC0de** [comment]
I would try firs hook plugins

**Comment by Ryan747800B** [comment]
@GammaC0de It's `AntiStandby`

**Comment by Ryan747800B** [comment]
Tried now to do a fresh install and I see that plugin.conf has already disabled AntiStanby but it doesn't works.I'm investigating the cause.

**Comment by Ryan747800B** [comment]
@GammaC0de I found what's wrong with `plugin.conf`: not only `AntiStanby` (must be `False`) but `DownloadScheduler` (must be `True`) too. Only thing is that today I reinstalled all and what I noticed is that `plugin.conf` is updated, and so the old `cat` doesn't work. So there is a way to not use `cat` method to modify that specific value, so that if pyLoad will be updated all works fine? Now I use this

```
# pyLoad Install - plugin.conf
cat <<"EOM" >/opt/etc/pyload/plugin.conf
...
DownloadScheduler - "DownloadScheduler":
	str timetable : "List time periods as hh:mm full or number(kB/s)" = 0:00 full, 7:00 250, 10:00 0, 17:00 150
	bool abort : "Abort active downloads when start period with speed 0" = False
	bool activated : "Activated" = True
...
EOM
```

Another thing: this is output debug; there are some errors but it seems all is working fine.

```
...
04.03.2016 00:34:06 ERROR     ADDON ClickNLoad: (98, 'Address already in use')
Traceback (most recent call last):
  File "/opt/lib/python2.5/threading.py", line 462, in __bootstrap
    self.__bootstrap_inner()
  File "/opt/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/etc/pyload/userplugins/hooks/ClickNLoad.py", line 103, in _server
    dock_socket.bind((self.cnl_ip, self.cnl_port))
  File "<string>", line 1, in bind
error: (98, 'Address already in use')

04.03.2016 00:38:06 ERROR     ADDON ClickNLoad: (98, 'Address already in use')
Traceback (most recent call last):
  File "/opt/lib/python2.5/threading.py", line 462, in __bootstrap
    self.__bootstrap_inner()
  File "/opt/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/etc/pyload/userplugins/hooks/ClickNLoad.py", line 103, in _server
    dock_socket.bind((self.cnl_ip, self.cnl_port))
  File "<string>", line 1, in bind
error: (98, 'Address already in use')

04.03.2016 00:42:06 ERROR     ADDON ClickNLoad: (98, 'Address already in use')
Traceback (most recent call last):
  File "/opt/lib/python2.5/threading.py", line 462, in __bootstrap
    self.__bootstrap_inner()
  File "/opt/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/etc/pyload/userplugins/hooks/ClickNLoad.py", line 103, in _server
    dock_socket.bind((self.cnl_ip, self.cnl_port))
  File "<string>", line 1, in bind
error: (98, 'Address already in use')
```

**Comment by Youkier** [comment]
@Ryan747800B I would like to put in place quite the same script (to move files once a download is finished)

Is it possible to have the final script you used ?

Thanks
