### ISSUE TITLE
UpdateManager - Error updating plugins

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2377]
With a fresh installation of pyLoad - using the tweaked UpdateManager `https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py` - plugins don't updates correctly. Yesterday it was all fine; some change in GitHub code yesterday?

Here the debug log

```
7.03.2016 05:56:12 INFO      Starting payload 0.4.9
07.03.2016 05:56:12 INFO      Using home directory: /opt/etc/pyload
07.03.2016 05:56:12 DEBUG     Remote activated: False
07.03.2016 05:56:13 DEBUG     created index of plugins
07.03.2016 05:56:13 INFO      ExternalScripts: Installed scripts for download_finished: ExternalScript.sh, SCRIPTS
07.03.2016 05:56:13 INFO      ExtractArchive: Activated UnRar
07.03.2016 05:56:14 INFO      Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
07.03.2016 05:56:14 INFO      Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
07.03.2016 05:56:14 INFO      Downloadtime: True
07.03.2016 05:56:14 INFO      Free space: 1.81 TiB
07.03.2016 05:56:14 INFO      Activating Accounts...
07.03.2016 05:56:14 INFO      Activating Plugins...
07.03.2016 05:56:14 INFO      pyLoad is up and running
07.03.2016 05:56:14 INFO      Starting threaded webserver: 0.0.0.0:8000
07.03.2016 05:56:16 INFO      UpdateManager: No Updates for payload
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/opt/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/share/pyload/module/plugins/hooks/UpdateManager.py", line 52, in periodical
    self.checkPlugins(updates)
  File "/opt/share/pyload/module/plugins/hooks/UpdateManager.py", line 136, in checkPlugins
    "version": float(version)
ValueError: empty string for float()
```

Using this script from @GammaC0de same thing

```
marks=( '/' '-' '\' '|' )

/opt/etc/init.d/pyload start
i=0
tail -f /opt/etc/pyload/Logs/log.txt | while read LOGLINE
do
    printf "\rpyLoad updating, please wait ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"please restart pyLoad"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; )
done
```

It hangs (see `115	07.03.2016 05:50:52	INFO	UpdateManager: New version of captcha|SolveMedia : 0.18`). It says 1`32 07.03.2016 05:56:16 INFO    UpdateManager: No Updates for pyload` but that's not true: there are a lot of updates missing.

```
07.03.2016 05:50:11	INFO	Starting payload 0.4.9
2	07.03.2016 05:50:11	INFO	Using home directory: /opt/etc/pyload
3	07.03.2016 05:50:13	INFO	ExternalScripts: Installed scripts for download_finished: ExternalScript.sh, SCRIPTS
4	07.03.2016 05:50:13	INFO	ExtractArchive: Activated UnRar
5	07.03.2016 05:50:13	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
6	07.03.2016 05:50:13	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
7	07.03.2016 05:50:13	INFO	Downloadtime: True
8	07.03.2016 05:50:13	INFO	Free space: 1.81 TiB
9	07.03.2016 05:50:13	INFO	Activating Accounts...
10	07.03.2016 05:50:13	INFO	Activating Plugins...
11	07.03.2016 05:50:13	INFO	pyLoad is up and running
12	07.03.2016 05:50:14	INFO	Starting threaded webserver: 0.0.0.0:8000
13	07.03.2016 05:50:16	INFO	UpdateManager: No Updates for payload
14	07.03.2016 05:50:16	INFO	UpdateManager: New version of account|AlldebridCom : 0.30
15	07.03.2016 05:50:16	INFO	UpdateManager: New version of account|AniStreamCom : 0.04
16	07.03.2016 05:50:17	INFO	UpdateManager: New version of account|BackinNet : 0.05
17	07.03.2016 05:50:18	INFO	UpdateManager: New version of account|BitshareCom : 0.19
18	07.03.2016 05:50:18	INFO	UpdateManager: New version of account|CatShareNet : 0.12
19	07.03.2016 05:50:19	INFO	UpdateManager: New version of account|CloudsharesNet : 0.02
20	07.03.2016 05:50:19	INFO	UpdateManager: New version of account|CloudsixMe : 0.04
21	07.03.2016 05:50:19	INFO	UpdateManager: New version of account|CloudzillaTo : 0.08
22	07.03.2016 05:50:20	INFO	UpdateManager: New version of account|CramitIn : 0.07
23	07.03.2016 05:50:20	INFO	UpdateManager: New version of account|CzshareCom : 0.26
24	07.03.2016 05:50:21	INFO	UpdateManager: New version of account|DebridItaliaCom : 0.19
25	07.03.2016 05:50:21	INFO	UpdateManager: New version of account|DepositfilesCom : 0.38
26	07.03.2016 05:50:21	INFO	UpdateManager: New version of account|EasybytezCom : 0.16
27	07.03.2016 05:50:22	INFO	UpdateManager: New version of account|EuroshareEu : 0.09
28	07.03.2016 05:50:22	INFO	UpdateManager: New version of account|ExashareCom : 0.05
29	07.03.2016 05:50:22	INFO	UpdateManager: New version of account|FastixRu : 0.10
30	07.03.2016 05:50:23	INFO	UpdateManager: New version of account|FastshareCz : 0.13
31	07.03.2016 05:50:23	INFO	UpdateManager: New version of account|File4SafeCom : 0.09
32	07.03.2016 05:50:23	INFO	UpdateManager: New version of account|FilecloudIo : 0.12
33	07.03.2016 05:50:24	INFO	UpdateManager: New version of account|FilefactoryCom : 0.21
34	07.03.2016 05:50:24	INFO	UpdateManager: New version of account|FilejokerNet : 0.01
35	07.03.2016 05:50:24	INFO	UpdateManager: New version of account|FilejungleCom : 0.18
36	07.03.2016 05:50:25	INFO	UpdateManager: New version of account|FileomCom : 0.06
37	07.03.2016 05:50:25	INFO	UpdateManager: New version of account|FilerNet : 0.11
38	07.03.2016 05:50:26	INFO	UpdateManager: New version of account|FilerioCom : 0.07
39	07.03.2016 05:50:26	INFO	UpdateManager: New version of account|FilesMailRu : 0.17
40	07.03.2016 05:50:26	INFO	UpdateManager: New version of account|FileserveCom : 0.26
41	07.03.2016 05:50:27	INFO	UpdateManager: New version of account|FourSharedCom : 0.12
42	07.03.2016 05:50:27	INFO	UpdateManager: New version of account|FreakshareCom : 0.19
43	07.03.2016 05:50:27	INFO	UpdateManager: New version of account|FreeWayMe : 0.21
44	07.03.2016 05:50:28	INFO	UpdateManager: New version of account|FshareVn : 0.16
45	07.03.2016 05:50:28	INFO	UpdateManager: New version of account|Ftp : 0.06
46	07.03.2016 05:50:29	INFO	UpdateManager: New version of account|HellshareCz : 0.25
47	07.03.2016 05:50:29	INFO	UpdateManager: New version of account|HighWayMe : 0.08
48	07.03.2016 05:50:29	INFO	UpdateManager: New version of account|Http : 0.06
49	07.03.2016 05:50:30	INFO	UpdateManager: New version of account|HugefilesNet : 0.06
50	07.03.2016 05:50:30	INFO	UpdateManager: New version of account|HundredEightyUploadCom : 0.07
51	07.03.2016 05:50:30	INFO	UpdateManager: New version of account|JunkyvideoCom : 0.05
52	07.03.2016 05:50:31	INFO	UpdateManager: New version of account|JunocloudMe : 0.06
53	07.03.2016 05:50:31	INFO	UpdateManager: New version of account|Keep2ShareCc : 0.12
54	07.03.2016 05:50:31	INFO	UpdateManager: New version of account|LetitbitNet : 0.08
55	07.03.2016 05:50:32	INFO	UpdateManager: New version of account|LinksnappyCom : 0.12
56	07.03.2016 05:50:32	INFO	UpdateManager: New version of account|MegaDebridEu : 0.26
57	07.03.2016 05:50:32	INFO	UpdateManager: New version of account|MegaRapidCz : 0.41
58	07.03.2016 05:50:33	INFO	UpdateManager: New version of account|MegaRapidoNet : 0.08
59	07.03.2016 05:50:33	INFO	UpdateManager: New version of account|MegasharesCom : 0.09
60	07.03.2016 05:50:33	INFO	UpdateManager: New version of account|MovReelCom : 0.07
61	07.03.2016 05:50:34	INFO	UpdateManager: New version of account|MultihostersCom : 0.07
62	07.03.2016 05:50:34	INFO	UpdateManager: New version of account|MultishareCz : 0.12
63	07.03.2016 05:50:34	INFO	UpdateManager: New version of account|MyfastfileCom : 0.10
64	07.03.2016 05:50:35	INFO	UpdateManager: New version of account|NitroflareCom : 0.11
65	07.03.2016 05:50:35	INFO	UpdateManager: New version of account|NoPremiumPl : 0.08
66	07.03.2016 05:50:35	INFO	UpdateManager: New version of account|NosuploadCom : 0.06
67	07.03.2016 05:50:36	INFO	UpdateManager: New version of account|NovafileCom : 0.06
68	07.03.2016 05:50:36	INFO	UpdateManager: New version of account|NowVideoSx : 0.09
69	07.03.2016 05:50:36	INFO	UpdateManager: New version of account|OboomCom : 0.31
70	07.03.2016 05:50:37	INFO	UpdateManager: New version of account|OneFichierCom : 0.21
71	07.03.2016 05:50:37	INFO	UpdateManager: New version of account|OpenloadCo : 0.02
72	07.03.2016 05:50:37	INFO	UpdateManager: New version of account|OverLoadMe : 0.11
73	07.03.2016 05:50:38	INFO	UpdateManager: New version of account|PremiumTo : 0.15
74	07.03.2016 05:50:38	INFO	UpdateManager: New version of account|PremiumizeMe : 0.24
75	07.03.2016 05:50:38	INFO	UpdateManager: New version of account|PutdriveCom : 0.06
76	07.03.2016 05:50:39	INFO	UpdateManager: New version of account|QuickshareCz : 0.09
77	07.03.2016 05:50:39	INFO	UpdateManager: New version of account|RPNetBiz : 0.19
78	07.03.2016 05:50:39	INFO	UpdateManager: New version of account|RapideoPl : 0.08
79	07.03.2016 05:50:40	INFO	UpdateManager: New version of account|RapidfileshareNet : 0.09
80	07.03.2016 05:50:40	INFO	UpdateManager: New version of account|RapidgatorNet : 0.18
81	07.03.2016 05:50:41	INFO	UpdateManager: New version of account|RapiduNet : 0.11
82	07.03.2016 05:50:41	INFO	UpdateManager: New version of account|RarefileNet : 0.08
83	07.03.2016 05:50:41	INFO	UpdateManager: New version of account|RealdebridCom : 0.52
84	07.03.2016 05:50:42	INFO	UpdateManager: New version of account|RehostTo : 0.23
85	07.03.2016 05:50:42	INFO	UpdateManager: New version of account|SafesharingEu : 0.06
86	07.03.2016 05:50:43	INFO	UpdateManager: New version of account|SecureUploadEu : 0.06
87	07.03.2016 05:50:43	INFO	UpdateManager: New version of account|SendmywayCom : 0.06
88	07.03.2016 05:50:43	INFO	UpdateManager: New version of account|SharebeastCom : 0.05
89	07.03.2016 05:50:44	INFO	UpdateManager: New version of account|ShareonlineBiz : 0.44
90	07.03.2016 05:50:44	INFO	UpdateManager: New version of account|SimplyPremiumCom : 0.12
91	07.03.2016 05:50:44	INFO	UpdateManager: New version of account|SimplydebridCom : 0.17
92	07.03.2016 05:50:45	INFO	UpdateManager: New version of account|SmoozedCom : 0.11
93	07.03.2016 05:50:45	INFO	UpdateManager: New version of account|StreamcloudEu : 0.06
94	07.03.2016 05:50:45	INFO	UpdateManager: New version of account|TurbobitNet : 0.09
95	07.03.2016 05:50:46	INFO	UpdateManager: New version of account|TusfilesNet : 0.10
96	07.03.2016 05:50:46	INFO	UpdateManager: New version of account|UlozTo : 0.16
97	07.03.2016 05:50:46	INFO	UpdateManager: New version of account|UploadableCh : 0.09
98	07.03.2016 05:50:47	INFO	UpdateManager: New version of account|UploadcCom : 0.06
99	07.03.2016 05:50:47	INFO	UpdateManager: New version of account|UploadedTo : 0.41
100	07.03.2016 05:50:47	INFO	UpdateManager: New version of account|UploadheroCom : 0.27
101	07.03.2016 05:50:48	INFO	UpdateManager: New version of account|UptoboxCom : 0.20
102	07.03.2016 05:50:48	INFO	UpdateManager: New version of account|VidPlayNet : 0.06
103	07.03.2016 05:50:48	INFO	UpdateManager: New version of account|WebshareCz : 0.14
104	07.03.2016 05:50:49	INFO	UpdateManager: New version of account|WorldbytezCom : 0.05
105	07.03.2016 05:50:49	INFO	UpdateManager: New version of account|YibaishiwuCom : 0.08
106	07.03.2016 05:50:50	INFO	UpdateManager: New version of account|ZeveraCom : 0.32
107	07.03.2016 05:50:50	INFO	UpdateManager: New version of captcha|AdYouLike : 0.10
108	07.03.2016 05:50:50	INFO	UpdateManager: New version of captcha|AdsCaptcha : 0.13
109	07.03.2016 05:50:51	INFO	UpdateManager: New version of captcha|CircleCaptcha : 1.08
110	07.03.2016 05:50:51	INFO	UpdateManager: New version of captcha|GigasizeCom : 0.16
111	07.03.2016 05:50:51	INFO	UpdateManager: New version of captcha|LinksaveIn : 0.17
112	07.03.2016 05:50:52	INFO	UpdateManager: New version of captcha|NetloadIn : 0.16
113	07.03.2016 05:50:52	INFO	UpdateManager: New version of captcha|ReCaptcha : 0.27
114	07.03.2016 05:50:52	INFO	UpdateManager: New version of captcha|ShareonlineBiz : 0.16
115	07.03.2016 05:50:52	INFO	UpdateManager: New version of captcha|SolveMedia : 0.18
116	07.03.2016 05:56:07	INFO	shutting down...
117	07.03.2016 05:56:07	INFO	Received Quit signal
118	07.03.2016 05:56:12	INFO	Starting payload 0.4.9
119	07.03.2016 05:56:12	INFO	Using home directory: /opt/etc/pyload
120	07.03.2016 05:56:12	DEBUG	Remote activated: False
121	07.03.2016 05:56:13	DEBUG	created index of plugins
122	07.03.2016 05:56:13	INFO	ExternalScripts: Installed scripts for download_finished: ExternalScript.sh, SCRIPTS
123	07.03.2016 05:56:13	INFO	ExtractArchive: Activated UnRar
124	07.03.2016 05:56:14	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
125	07.03.2016 05:56:14	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
126	07.03.2016 05:56:14	INFO	Downloadtime: True
127	07.03.2016 05:56:14	INFO	Free space: 1.81 TiB
128	07.03.2016 05:56:14	INFO	Activating Accounts...
129	07.03.2016 05:56:14	INFO	Activating Plugins...
130	07.03.2016 05:56:14	INFO	pyLoad is up and running
131	07.03.2016 05:56:14	INFO	Starting threaded webserver: 0.0.0.0:8000
132	07.03.2016 05:56:16	INFO	UpdateManager: No Updates for payload
```

**Comment by GammaC0de** [comment]
The problem relies in https://github.com/pyload/pyload/commit/e4fc68fee71f2bfee57932a04800406f44bdbf16.
This is what happens when a plugin has no `__version__` string.

**Comment by GammaC0de** [comment]
Now http://updatemanager.pyload.org/?v=0.4.9 does not update :-1: 
@vuolter @stickell Please advise.

**Comment by Ryan747800B** [comment]
I do not know how exactly pyLoad handles updates, but would it not be better for all updates structure to have a redundant UpdateManager maybe on GitHub or something similar?

**Comment by GammaC0de** [comment]
@Ryan747800B We do our best but there will always be surprises.

**Comment by Ryan747800B** [comment]
@GammaC0de :thumbsup:

**Comment by sodd** [comment]
sorry for that issue... :rainbow:

**Comment by GammaC0de** [comment]
@sodd That's ok

**Comment by sodd** [comment]
Is it possible to have some testing environment which will test witch PR is good and witch is bad? I have zero experience with this so my apologies if this is dummy question.

**Comment by Ryan747800B** [comment]
How's the UpdateManager status now? Have you figured out why it doesn't work anymore? I can help in some way?

**Comment by GammaC0de** [comment]
https://github.com/pyload/updatemanager/issues/39

**Comment by Ryan747800B** [comment]
@GammaC0de Issue is probably [here;](http://updatemanager.pyload.org/?v=0.4.9) as you can see, `UlozTo` hasn't version number.

```
captcha|SolveMedia.py|93192da|0.18
captcha|UlozTo.py|e4fc68f|
container|CCF.py|fd4ff4e|0.28
```

I tried to download that html, delete line 186 (`UlozTo`) and modify `UpdateManager.py`, so it redirects to a modded `UpdateMnanager.html` but it doesn't work. All done with a fresh install.

**Comment by mcmikele** [comment]
any Update ? Its still not working :(

**Comment by johenning** [comment]
@mcmikele This might help you. I changed line 286 in UpdateManager.py from `newver = float(plugin_version)` to `newver = float(plugin_version) if not len(plugin_version) == 0 else 0`
Which is probably not the right way to test for empty string, but pyload didn't crash on start and updated the Updater to a newer version that handles missing version numbers on its own.

**Comment by GammaC0de** [comment]
@johenning @mcmikele `UpdateManager` v1.11 already handles this situation.
Please update your `UpdateManager` manually if its not updated already:
https://github.com/pyload/pyload/raw/stable/module/plugins/hooks/UpdateManager.py

**Comment by mcmikele** [comment]
it didnt help, i tried it already 2 days ago

**Comment by Ryan747800B** [comment]
@GammaC0de is that UpdateManager URL the definitive one or is it only temporary? Because of if you remember, I use with my script this UpdateManager `https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py`. What are the differences between these two? Should I use the new one as future reference?

**Comment by GammaC0de** [comment]
@mcmikele `UpdateManager` v1.11 should work - it  would log an error about `UlozTo` (because there actually an error with it) but it should continue updating other plugins, isn't that the case?

@Ryan747800B the above url (https://github.com/pyload/pyload/raw/stable/module/plugins/hooks/UpdateManager.py) is of the **latest** version of  `UpdateManager`, it would not work with the release version of `pyLoad` because it depends on internal plugins that are not yet updated.

https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py is the right version to work with in your case but this version fails to overcome the current issue with no version info in http://updatemanager.pyload.org/?v=0.4.9

So the only option for you (until this issue is fixed) is to use your own custom version of https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py that knows how to deal with the current issue - see how it was done in https://github.com/pyload/pyload/commit/ed91dde1c52851bbfd1168620328b7809a3623f8

**Comment by Ryan747800B** [comment]
@GammaC0de Ok, but it's not clear to me how can I add that modifications; I mean, those two files are really different (375 vs 201 lines). I simply add those additional lines at the end of `https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py` ?

**Comment by GammaC0de** [comment]
@Ryan747800B see https://github.com/pyload/pyload/commit/ed91dde1c52851bbfd1168620328b7809a3623f8 how it was fixed for v1.10 and adapt that to your version.

**Comment by dannyshirt** [comment]
I also have troubles getting the UpdateManager to work. Could someone give a brief step-by-step tutorial on how to fix the UpdateManager on a fresh installation of pyLoad?

**Comment by mcmikele** [comment]
UpdateManager is still not working :/ 
I installed pyload new and changed the UpdateManager.py file, but it doesnt start to update.
Am i the only who has actually Problems with pyload. Cpl months ago i had also big trouble with pyload UpdateManager. Is there something happening with Pyload ? Because it was working for years super stable, but since cpl months it changed :/

**Comment by Agomy** [comment]
So the original File doesn't update at all as it can't connect to the Update server.
The version 1.0 Creates the initial error and version 1.10 doesn't even try to run a update but also gives no error message except if you try to change the settings trough the webinterface then you get in the console:
`ERROR     Error importing UpdateManager: No module named Addon` 

So i do also not understand what needs to be modified manually to get it running again.

**Comment by GammaC0de** [comment]
@Ryan747800B @mcmikele @Agomy 
See #2000 on how to do a fresh install
Use https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/e67c25e144991612519940a67d8417ea43069a66/UpdateManager.py instead the one that is mentioned in #2000

**Comment by Agomy** [comment]
@GammaC0de Thank you so much, working again now.

**Comment by vuolter** [comment]
Anyway the new updatemanger is over the edge.

**Comment by GammaC0de** [comment]
@vuolter People with a new installation or people that had deleted their userplugins would still have to use the old update method, unless you will release a new pyload package..

**Comment by mcmikele** [comment]
URL :  "http://updatemanager.pyload.org"
URL : "http://updatemanager-spyload.rhcloud.com"

why did you use a other url ? Is that .....rhccloud.com url also ok ? 
I thought the .......pyload.org url is the official one

**Comment by GammaC0de** [comment]
@mcmikele This is just a historical version of `UpdateManager` (https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py) with a small change I made that can deal with #2377

**Comment by mcmikele** [comment]
i just worry about this url: "http://updatemanager-spyload.rhcloud.com" . Is that url reliable ?

**Comment by GammaC0de** [comment]
It should be safe, it supposed to be an alias but you can change to http://updatemanager.pyload.org/ if you like.

‫

**Comment by vuolter** [comment]
@GammaC0de I plan to release a 0.4.9-hotfix u_u

**Comment by mcmikele** [comment]
it is possible to update pyload (plugins) also manually without using updatemanager ? Which steps i have to do ?
Thx for the support. Especially to GammaCOde !

**Comment by GammaC0de** [comment]
@mcmikele see #2241

**Comment by mcmikele** [comment]
Thank u very much. Thx for that awesome support !!!!!!!!!!!!!!!!!

**Comment by GammaC0de** [comment]
:+1:

**Comment by mcmikele** [comment]
Have one more question :)
I updated pyload manually and i just found out that ExtractArchive is not working. Its activated but it doesnt start to unpack the rar's. Is this problem connected with my manually update ? Its the only problem i have.

**Comment by GammaC0de** [comment]
ExtractArchive  not working ATM, see #2296

**Comment by GammaC0de** [comment]
fixed
