### ISSUE TITLE
DLC decyption failed

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#2819]
decryption dlc container failed, maybe since yesterday! It seems a webservice is down:

```379	08.04.2017 11:59:51	INFO	Decrypting starts: /home/blah/.pyload/Downloads/tmp_blah.dlc
380	08.04.2017 11:59:51	WARNING	CONTAINER DLC[636]: Plugin may be unstable
381	08.04.2017 11:59:51	INFO	CONTAINER DLC[636]: Grabbing link info...
382	08.04.2017 11:59:51	INFO	CONTAINER DLC[636]: Link name: tmp_blah.dlc
383	08.04.2017 11:59:51	INFO	CONTAINER DLC[636]: Link size: N/D
384	08.04.2017 11:59:51	INFO	CONTAINER DLC[636]: Link status: starting
385	08.04.2017 11:59:51	INFO	CONTAINER DLC[636]: Processing url: /home/blah/.pyload/Downloads/tmp_blah.dlc
386	08.04.2017 11:59:51	ERROR	Decrypting failed: tmp_blah.dlc | Bad server response: 500 Internal Server Error

**Comment by noyse27** [comment]
The problem has been 3 or 4 days.

**Comment by led13714** [comment]
I am currently having the same issue as @Web-Eye

**Comment by mkli90** [comment]
dito

**Comment by Web-Eye** [comment]
Yeah,
it seems to every decrypter service use linkdecrypter.com to work! But however JD decryption works, maybe they have there own dycrypter service.

**Comment by GammaC0de** [comment]
@Web-Eye DLC file format is an invention of JDownloader.
Being so, every DLC link decrypter must use JDownloader's web services to decrypt them.
Without it , it cannot be decrypted.

Recently they changed something on their servers that causes this issue.
I'm trying to figure what they changed and how to deal with it.

**Comment by Coalado** [comment]
Hey their. This is a JD issue. After years, our dlc server crashed, and we rewrote it.
We are currectly implementing the pyload encryption. It actually should work, but pyload keeps on having decryption  issues. @GammaC0de : Could you please join our, or the #pyload channel to fix this issue together asap?

**Comment by GammaC0de** [comment]
@Coalado do you mean \#pyload IRC channel?

**Comment by Coalado** [comment]
I hope that this is fixed. The new server code uses different encryption libraries. Nevertheless, from my point of view, the service works like it did before.

**Comment by Coalado** [comment]
UPDATE: We fixed the padding on our server. Your "FIX" is not required anymore and can be reverted.

**Comment by DeaconF** [comment]
@GammaC0de it still does not work. I got Plugin Update 2 Days ago but still get same error
`12.04.2017 13:10:31	INFO	Added package add_file containing 1 links
1033	12.04.2017 13:10:31	INFO	Decrypting starts: inbox/tmp_0820d9faf45c62e9e70d3b9cdb147118c50e2282.dlc
1034	12.04.2017 13:10:31	WARNING	CONTAINER DLC[1]: Plugin may be unstable
1035	12.04.2017 13:10:31	INFO	CONTAINER DLC[1]: Grabbing link info...
1036	12.04.2017 13:10:31	INFO	CONTAINER DLC[1]: Link name: tmp_0820d9faf45c62e9e70d3b9cdb147118c50e2282.dlc
1037	12.04.2017 13:10:31	INFO	CONTAINER DLC[1]: Link size: N/D
1038	12.04.2017 13:10:31	INFO	CONTAINER DLC[1]: Link status: starte
1039	12.04.2017 13:10:31	INFO	CONTAINER DLC[1]: Processing url: inbox/tmp_0820d9faf45c62e9e70d3b9cdb147118c50e2282.dlc
1040	12.04.2017 13:10:31	ERROR	Decrypting failed: tmp_0820d9faf45c62e9e70d3b9cdb147118c50e2282.dlc | Bad server response: 500 Internal Server Error `

**Comment by noyse27** [comment]
i'm using pyload on synology without any update and it works again since 2
days

2017-04-12 13:27 GMT+02:00 DeaconF <notifications@github.com>:

**Comment by Coalado** [comment]
@DeaconF  during the downtime, several services created bad dlc files (no errorHandling). Instead of the key, they appended the server adress to the dlc file. These dlcs are broken. The server answers with a 500 response. Redownload the dlc

**Comment by DeaconF** [comment]
@Coalado thank you i will try it
